services:

  postgres:
    image: postgres:16-alpine
    container_name: smartvideo-postgres

    environment:
      POSTGRES_DB: smartvideo
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: